logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "universal"
build-mode = "module"
version = "auto"
included-patches = "client-spoof custom-branding hide-ads hide-floating-microphone-button minimized-playback navigation-buttons old-quality-layout premium-heading remember-video-quality return-youtube-dislike sponsorblock tablet-mini-player theme video-ads video-speed wide-searchbar"
exclusive-patches = true

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"
build-mode = "module"
version = "auto"

[Photomath]
enabled = true
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"
